version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - '80:80' # HTTP
      - '443:443' # HTTPS
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - full-stack-network
    command: ['nginx', '-g', 'daemon off;']
    environment:
      - NGINX_HOST=user-management.local
      - NGINX_PROXY=nestjs:3000

  avahi:
    image: flungo/avahi
    container_name: avahi
    network_mode: host # Required for mDNS
    restart: always
    environment:
      - AVAHI_START_DAEMON=true # Start Avahi daemon
      - DISABLE_SYSTEMD=true # Disable systemd (not used in container)
    volumes:
      - ./avahi-config:/etc/avahi # Optional: Custom configuration

  postfix:
    image: boky/postfix:latest
    container_name: postfix
    restart: always
    environment:
      - POSTFIX_myhostname=user-management.local
      - POSTFIX_smtp_sasl_auth_enable=yes
      - POSTFIX_smtp_sasl_password_maps=static:your_smtp_username:your_smtp_password
      - POSTFIX_smtp_sasl_security_options=noanonymous
      - ALLOW_EMPTY_SENDER_DOMAINS=true
      - POSTFIX_LOG_LEVEL=debug # Enable detailed logging
    ports:
      - '25:25' # SMTP
    volumes:
      - ./config/postfix:/etc/postfix # Mounting the postfix config directory
      - ./config/supervisord.conf:/etc/supervisor/supervisord.conf # Ensure custom supervisord.conf is used
    networks:
      - full-stack-network
    command: >
      sh -c "sleep 5 && postalias /etc/postfix/aliases && supervisord -c /etc/supervisor/supervisord.conf"  # Added delay for proper startup

  dovecot:
    image: instrumentisto/dovecot
    container_name: dovecot
    restart: always
    environment:
      - DOVECOT_PROTOCOLS=imap pop3
    ports:
      - '143:143' # IMAP
      - '110:110' # POP3
    volumes:
      - ./data/mail:/var/mail
      - ./config/dovecot:/etc/dovecot
      - ./config/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf # Ensure the config file exists
    networks:
      - full-stack-network

  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=hive-db
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - full-stack-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
      - SCRIPT_NAME=/pgadmin
    ports:
      - '5050:80'
    networks:
      - full-stack-network
    volumes:
      - pgadmin:/var/lib/pgadmin # Ensure pgAdmin has its own volume

  nestjs:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Dockerfile is at the top level
    container_name: nestjs
    restart: always
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=hive-db
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - full-stack-network

volumes:
  postgres:
  pgadmin: # Define separate volume for pgAdmin to avoid any overlap with other services

networks:
  full-stack-network:
    driver: bridge
