version: '3.8'

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=hive-db # Optional: specify a default database
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - pg-network # Use an explicit network for better isolation

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres # Ensure pgAdmin starts after PostgreSQL
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - '5050:80'
    networks:
      - pg-network # Connect pgAdmin to the same network as PostgreSQL

volumes:
  postgres:

networks:
  pg-network: # Define an explicit network for service communication

