version: '3.8'

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=hive-db # Optional: specify a default database
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - pg-network # Use an explicit network for better isolation

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres # Ensure pgAdmin starts after PostgreSQL
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - '5050:80'
    networks:
      - pg-network # Connect pgAdmin to the same network as PostgreSQL

  postfix:
    image: alpine:latest
    container_name: postfix
    environment:
      - MAILDOMAIN=localhost # Replace with a real domain for production
      - MAILHOST=localhost
      - SMTP_USER=user:password
      - SMTP_TLS_CERT=./certs/postfix/postfix.crt # Path to SSL certificate
      - SMTP_TLS_KEY=./certs/postfix/postfix.key # Path to SSL key
    volumes:
      - /etc/postfix
      - ./certs/postfix:/etc/postfix/ssl:ro # Mount certificate and key
    ports:
      - '25:25' # SMTP (non-encrypted)
      - '465:465' # SMTP (SSL-encrypted)
      - '587:587' # SMTP (STARTTLS)
    networks:
      - mailing-network
    command: >
      sh -c "apk update && apk add --no-cache postfix && postfix start-fg"

  dovecot:
    image: dovecot/dovecot
    container_name: dovecot
    environment:
      - MAILDOMAIN=localhost # Replace with a real domain for production
    volumes:
      - /etc/dovecot
      - ./certs/dovecot:/etc/dovecot/ssl:ro # Mount certificate and key
    ports:
      - '143:143' # IMAP (non-SSL)
      - '993:993' # IMAP (SSL-encrypted)
    networks:
      - mailing-network
    command: >
      sh -c "dovecot -F"

volumes:
  postgres:

networks:
  pg-network: # Define an explicit network for db service communication
  mailing-network: # Define an explicit network for mailing service communication
    driver: bridge
