services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      full-stack-network:
        aliases:
          - adminer
    command: ['nginx', '-g', 'daemon off;']
    env_file:
      - .env
    depends_on:
      - adminer # Ensure Nginx waits for Adminer service to be up

  avahi:
    image: flungo/avahi
    container_name: avahi
    network_mode: host
    restart: always
    env_file:
      - .env
    volumes:
      - ./avahi-config:/etc/avahi
    hostname: ${AVAHI_HOSTNAME}
    command:
      - /bin/sh
      - -c
      - |
        /usr/sbin/avahi-daemon &
        sleep 35
        tail -f /dev/null

  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - full-stack-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 20s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080' # Adminer's web UI exposed on port 8080 externally
    networks:
      - full-stack-network
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres'
      ADMINER_DEFAULT_DB: ${POSTGRES_DB}
      ADMINER_DEFAULT_USER: ${POSTGRES_USER}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}

  nestjs:
    build:
      context: .
      dockerfile: nest.Dockerfile
    container_name: nestjs
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - full-stack-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: '${DATABASE_URL_PROD}'
    command:
      [
        'sh',
        '-c',
        '/wait-for-it.sh postgres:5432 --timeout=30 --strict -- yarn start:prod',
      ]

volumes:
  postgres:

networks:
  full-stack-network:
    driver: bridge
