version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - '80:80' # HTTP
      - '443:443' # HTTPS
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - full-stack-network
    command: ['nginx', '-g', 'daemon off;']
    environment:
      - NGINX_HOST=user-management.local
      - NGINX_PROXY=nestjs:3000

  avahi:
    image: flungo/avahi
    container_name: avahi
    network_mode: host # Required for mDNS
    restart: always
    environment:
      - AVAHI_START_DAEMON=true # Start Avahi daemon
      - DISABLE_SYSTEMD=true # Disable systemd (not used in container)
    volumes:
      - ./avahi-config:/etc/avahi # Optional: Custom configuration

  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=hive-db
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - full-stack-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - '5050:80'
    networks:
      - full-stack-network

  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    restart: always
    env_file:
      - .env.mailserver
    hostname: mail
    domainname: user-management.net
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_POSTFIX=1
      - ENABLE_DOVECOT=1
      - ENABLE_RSPAMD=1
    volumes:
      - ./data/mail:/var/mail
      - ./data/state:/var/lib/dovecot
      - ./data/config:/etc/mailserver
      - ./data/certs:/etc/letsencrypt
    networks:
      - full-stack-network

  nestjs:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Dockerfile is at the top level
    container_name: nestjs
    restart: always
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=hive-db
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - full-stack-network

volumes:
  postgres:

networks:
  full-stack-network:
    driver: bridge
