version: '3.8'

services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=hive-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - full-stack-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
      - SCRIPT_NAME=/pgadmin
    ports:
      - '5050:80'
    networks:
      - full-stack-network
    volumes:
      - pgadmin:/var/lib/pgadmin

  # postfix:
  #   image: boky/postfix:latest
  #   container_name: postfix
  #   restart: always
  #   environment:
  #     - POSTFIX_myhostname=user-management.local
  #     - POSTFIX_smtp_sasl_auth_enable=yes
  #     - POSTFIX_smtp_sasl_password_maps=static:your_smtp_username:your_smtp_password
  #     - POSTFIX_smtp_sasl_security_options=noanonymous
  #     - ALLOW_EMPTY_SENDER_DOMAINS=true
  #     - POSTFIX_LOG_LEVEL=debug
  #   ports:
  #     - '25:25'
  #   volumes:
  #     - ./config/postfix:/etc/postfix
  #     - ./config/supervisord.conf:/etc/supervisor/supervisord.conf
  #   networks:
  #     - full-stack-network
  #   command: >
  #     sh -c "sleep 5 && postalias /etc/postfix/aliases && supervisord -c /etc/supervisor/supervisord.conf"

  # dovecot:
  #   image: instrumentisto/dovecot
  #   container_name: dovecot
  #   restart: always
  #   environment:
  #     - DOVECOT_PROTOCOLS=imap pop3
  #   ports:
  #     - '143:143'
  #     - '110:110'
  #   volumes:
  #     - ./data/mail:/var/mail
  #     - ./config/dovecot:/etc/dovecot
  #     - ./config/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
  #   networks:
  #     - full-stack-network

volumes:
  postgres:
  pgadmin:

networks:
  full-stack-network:
    driver: bridge
