services:
  nginx:
    build:
      context: ../ # Project root as build context
      dockerfile: ./docker/nginx/nginx.localarea.Dockerfile
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/certs:/etc/nginx/certs # Bind mount with './'
      - ./nginx/nginx.localarea.conf:/etc/nginx/nginx.conf
    networks:
      full-stack-network:
        aliases:
          - adminer
    command: ['nginx', '-g', 'daemon off;']
    env_file:
      - ./.env # .env file in the docker folder

  avahi:
    image: flungo/avahi
    container_name: avahi
    network_mode: host
    restart: always
    env_file:
      - ./.env # .env file in the docker folder
    volumes:
      - ./avahi-config:/etc/avahi # Bind mount with './'
    hostname: ${AVAHI_HOSTNAME}
    command:
      - /bin/sh
      - -c
      - |
        rm -rf /var/run/avahi-daemon/*
        /usr/sbin/avahi-daemon &
        sleep 35
        tail -f /dev/null

  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    env_file:
      - ./.env # .env file in the docker folder
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - full-stack-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 20s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    env_file:
      - ./.env # .env file in the docker folder
    ports:
      - '8080:8080'
    networks:
      - full-stack-network
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres'
      ADMINER_DEFAULT_DB: ${POSTGRES_DB}
      ADMINER_DEFAULT_USER: ${POSTGRES_USER}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}

  nestjs:
    build:
      context: ../ # Project root for backend build
      dockerfile: ./docker/nest.Dockerfile
    container_name: nestjs
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./.env # .env file in the docker folder
      - ../apps/backend/.env # Backend-specific env file (relative to project root)
    networks:
      - full-stack-network
    depends_on:
      postgres:
        condition: service_healthy
    command:
      [
        'sh',
        '-c',
        '/wait-for-it.sh postgres:5432 --timeout=30 --strict -- yarn start:prod',
      ]

volumes:
  postgres:

networks:
  full-stack-network:
    driver: bridge
